Build
penguineer/mqtt-tools pull request #2
Opened 2017-10-01 21:15 UTC by LeSpocky

Some more or less trivial build fixes. Makes it a little easier for others to try this out and play with it.

2017-10-05 06:15 UTC, LeSpocky commented on mqtt-clock.c
I think this is a real bugfix and should be in an extra commit.

2017-10-05 08:41 UTC, penguineer commented on mqtt-clock.c
> -  int ret;
This is pure clean-up, should also be an extra commit.

2017-10-05 08:43 UTC, penguineer commented
Thanks for the PR. I have a not-yet-pushed branch of a further development state for this library, which I will check against your proposal. 

I'll comment when this is done (to avoid unnecessary work).

2017-10-05 19:14 UTC, penguineer requested changes
Please split this commit into:
1) One commit fixing the code
2) One commit changing the build environment.

Either in this PR or as a new PR. I'll integrate the result.
Thanks.

2017-10-06 06:38 UTC, LeSpocky commented
Splitted the requested commit. Note: there are still compiler warnings left, I did not fix, all of the type _return-type_ aka "control reaches end of non-void function".

2017-10-06 11:35 UTC, penguineer approved these changes

2017-10-06 11:37 UTC, merged

2017-10-06 11:39 UTC, penguineer commented
Thanks, I've merged,

(nb: Most editors can be set to fix whitespace issues only in lines which have been changed anyway.)